
export const DATA_REQUEST="DATA_REQUEST"
export const DATA_SUCCESS="DATA_SUCCESS"
export const DATA_FAILURE="DATA_FAILURE"

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";